### ISSUE TITLE
Is these Plugin alive?

### ISSUE THREAD

**Issue by mister-man** [pie-flavor/SpongyCord#1]
Hallo together,

I tried to post in the sponge form, but it seems that a post or a plugin download at sponge is impossible. Is these plugin alive? Because I'm searching for a way to teleport player through a bungee network of sponge server with signs etc

**Comment by pie-flavor** [comment]
The plugin doesn't need to be alive. Everything works as is.

**Comment by mister-man** [comment]
ogg... okay :)

My misstake, I found the plugin that use these api. Its Project potals. Thanks a lot for these work. 

Thanks :)
