### ISSUE TITLE
Seperate SpongyCord from being plugin dependant 

### ISSUE THREAD

**Issue by markhughes** [pie-flavor/SpongyCord#4]
Perhaps add a method to the API class so we can shadow in the library, instead of requiring it as another plugin?

Example..

```java
    public static void enable(Game game, Class<?> plugin) {
        channel = game.getChannelRegistrar().createRawChannel(plugin, "BungeeCord");
        channel.addListener(Platform.Type.SERVER, API.listener = new API.ChannelListener());
    }
    public static void disable(Game game, Class<?> plugin) {
        // ... etc 
```

(but I'm sure theres more to do here, just a quick idea)

**Comment by pie-flavor** [comment]
It's due for somewhat of a rewrite (I'm lucky more plugins don't use it, else we'd have problems with the fact that they're all sharing a single channel). When Ore comes back up, I'll change it.

**Comment by markhughes** [comment]
Great! I'm really looking forward to it. 🍻
