### ISSUE TITLE
The old download links are broken

### ISSUE THREAD

**Issue by KiriCattus** [pie-flavor/SpongyCord#6]
Download links from spongepowered are broken and I can't find the project on ore either. Could you update these when you have time please :) 

https://forums.spongepowered.org/t/spongycord-a-simple-wrapper-api-for-bungee/15678
https://ore-staging.spongepowered.org/pie_flavor/SpongyCord
(remove the "-staging" from the above url)

I have since found another post about the plugin at the link below... Apologies but best to let you know anyway so you can fix it :s

https://forums.spongepowered.org/t/door-spongycord-a-simple-wrapper-api-for-bungee/13216

**Comment by pie-flavor** [comment]
This project is deprecated, and [BungeeLib](https://github.com/pie-flavor/BungeeLib) should be used instead.

**Comment by KiriCattus** [comment]
Sure thing. Is there much difference between the two projects?

**Comment by pie-flavor** [comment]
Yes. SpongyCord is a plugin, installed separately and interfaced with by plugins. BungeeLib is a non-plugin library which developers should bundle with their plugins.

**Comment by KiriCattus** [comment]
Thanks for the update I'll close this off and figure out what plugin actually needed it lol sorry to bother you
